<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>compartilhei-api-secrets</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Contracts\Photos\RequestUpload\NovaPasta\**" />
    <Content Remove="Contracts\Photos\RequestUpload\NovaPasta\**" />
    <EmbeddedResource Remove="Contracts\Photos\RequestUpload\NovaPasta\**" />
    <None Remove="Contracts\Photos\RequestUpload\NovaPasta\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.11.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Compartilhei.Application\Compartilhei.Application.csproj" />
    <ProjectReference Include="..\Compartilhei.Infrastructure\Compartilhei.Infrastructure.csproj" />
  </ItemGroup>

</Project>
